#+TITLE: Emacs General Settings
#+AUTHOR: Spenser Pothier
#+EMAIL: mail@spenser.io
#+DATE: [2016-08-12]
#+TAGS: emacs

* Introduction
General settings

** Setup package manager
#+BEGIN_SRC emacs-lisp
;; Package manager
(require 'package)
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
(setq package-enable-at-startup nil)
#+END_SRC

** Function to ensure packages are installed
#+BEGIN_SRC emacs-lisp
(defun ensure-package-installed (&rest packages)
  "Assure every package is installed, ask for installation if it’s not.

Return a list of installed packages or nil for every skipped package."
  (mapcar
   (lambda (package)
     (if (package-installed-p package)
         nil
       (if (y-or-n-p (format "Package %s is missing. Install it? " package))
           (package-install package)
         package)))
   packages))

;; Make sure to have downloaded archive description.
(or (file-exists-p package-user-dir)
    (package-refresh-contents))
(package-initialize)
#+END_SRC
** List of packages
#+BEGIN_SRC emacs-lisp
;; Packages
(ensure-package-installed 'evil
			  'powerline
			  'powerline-evil
			  'auto-complete
			  'key-chord
			  'helm
			  'helm-ls-git
			  'projectile
			  'helm-projectile
			  'org-bullets
			  'org-beautify-theme
                          'git-gutter+
                          'magit
			  'smtpmail
			  'robe
			  'inf-ruby
			  'ledger-mode
			  'ruby-mode
			  'rubocop
			  'org-trello
			  'markdown-mode
			  'writeroom-mode
			  'mediawiki
			  'sr-speedbar
			  'rbenv
			  'rspec-mode)
#+END_SRC
** Evil mode settings
Evil mode is VIM key bindings within emacs
#+BEGIN_SRC emacs-lisp
(evil-mode t)

;; Use jk as escape for evil mode 
(setq key-chord-two-keys-delay 0.5)
(key-chord-define evil-insert-state-map "jk" (lambda() (interactive) (evil-normal-state) (evil-forward-char)))
(key-chord-mode 1)
(define-key org-mode-map (kbd "C-i") 'org-cycle)
;; Powerline evilmode
(powerline-evil-vim-color-theme)
#+END_SRC
** GUI settings
#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
(toggle-scroll-bar -1)
(load-theme 'wombat)
#+END_SRC
   
#+BEGIN_SRC emacs-lisp
(setq sr-speedbar-auto-refresh nil)
(setq speedbar-show-unknown-files t) ; show all files
(setq sr-speedbar-right-side nil) ; put on left side
#+END_SRC
** Settings for autosave
#+BEGIN_SRC emacs-lisp
(setq
   backup-by-copying t      ; don't clobber symlinks
   backup-directory-alist
    '(("." . "~/.saves"))    ; don't litter my fs tree
   delete-old-versions t
   kept-new-versions 6
   kept-old-versions 2
   version-control t)       ; use versioned backups
#+END_SRC
** Autocomplete settings
#+BEGIN_SRC emacs-lisp
(ac-config-default)
#+END_SRC
** Enable GitGutter+

#+BEGIN_SRC emacs-lisp
(global-git-gutter+-mode)
#+END_SRC

* Helm
Helm is for navigating. I'll make this intro better later

** Init
#+BEGIN_SRC emacs-lisp
(require 'helm-config)
(helm-mode 1)
#+END_SRC
** projectile
#+BEGIN_SRC emacs-lisp
(helm-projectile-on)
#+END_SRC
** Use helm for buffer navigation
#+BEGIN_SRC emacs-lisp 
(global-set-key (kbd "C-x b") 'helm-buffers-list)
#+END_SRC

** Use helm for bookmarks
#+BEGIN_SRC emacs-lisp 
(global-set-key (kbd "C-x r b") 'helm-bookmarks)
#+END_SRC
** Use helm for M-x commands
#+BEGIN_SRC emacs-lisp 
(global-set-key (kbd "C-x m") 'helm-M-x)
#+END_SRC
** Tabcomplete in find file
#+BEGIN_SRC emacs-lisp
(define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
#+END_SRC
** Projectile navigation
#+BEGIN_SRC emacs-lisp
(projectile-global-mode)
#+END_SRC

* Org Mode
** About Org mode
  [[http://orgmode.org][Org Mode]] was a feature of emacs that had always kept my interest, but the learning curve of emacs seemed daunting. I recently learned about [[https://www.emacswiki.org/emacs/Evil][Evil Mode]] which allows the use of VIM keybindings in emacs. Over the course of a few days, I became about 70-80% as quick getting around projects as I was with VIM. So with that in mind, I've been working on setting up emacs and learning how to use some of the powerful features it has that VIM is lacking. This file contains my org-mode settings, and uses a neat feature of org-mode called [[http://orgmode.org/manual/Extracting-source-code.html]["tangling"]]. See the bottom of the raw file for some details on how it is exported to the right location.
** Babel Setings 
  These settings are for loading up languages to use with [[http://orgmode.org/worg/org-contrib/babel/intro.html#literate-programming][babel]]
#+BEGIN_SRC emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '(
   (python . t)
   (ruby . t)
   (sh . t)
   (plantuml . t)
   ))
(setq org-plantuml-jar-path "/usr/share/plantuml/plantuml.jar")
(setq org-src-preserve-indentation t)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+END_SRC
* Mu4e and OfflineImap
#+BEGIN_SRC emacs-lisp
(setq mu4e-maildir "/home/spenser/Maildir")
(setq mu4e-sent-folder   "/INBOX.Sent Items"
      mu4e-drafts-folder "/INBOX.Drafts"
      mu4e-trash-folder  "/INBOX.Trash")
      

;; enable inline images
(setq mu4e-view-show-images t)
;; use imagemagick, if available
(when (fboundp 'imagemagick-register-types)
  (imagemagick-register-types))

(require 'mu4e-contrib)
(setq mu4e-html2text-command 'mu4e-shr2text)
(setq
   user-mail-address "mail@spenser.io"
   user-full-name  "Spenser Pothier"
   mu4e-compose-signature
    (concat
      "Spenser Pothier\n"
      "https://spenser.io\n"))

(setq message-send-mail-function 'smtpmail-send-it
     smtpmail-stream-type 'starttls
     smtpmail-default-smtp-server "mail.messagingengine.com"
     smtpmail-smtp-server "mail.messagingengine.com"
     smtpmail-smtp-service 587)

(setq mu4e-get-mail-command "offlineimap")
(setq mail-user-agent 'mu4e-user-agent)
(setq message-kill-buffer-on-exit t)
(defvar ac-source-contacts
  '((candidates . mu4e~contacts-for-completion)
    (prefix . "^\\(?:To\\|CC\\|BCC\\): \\(?:.*, *\\)?\\(.*\\)")))
 
(add-hook 'mu4e-compose-mode-hook
          (lambda()
            (setq ac-sources '(ac-source-contacts))
            (auto-complete-mode)))

(require 'org-mu4e)
#+END_SRC
* Item
#+OPTIONS:     :tangle yes
* Ledger Mode
Ledger mode stuff

#+BEGIN_SRC emacs-lisp
(autoload 'ledger-mode "ledger-mode" "A major mode for Ledger" t)
;(add-to-list 'load-path
;             (expand-file-name "/path/to/ledger/source/lisp/"))
(add-to-list 'auto-mode-alist '("\\.ledger$" . ledger-mode))
#+END_SRC

* Ruby/Rode
Settings related to robe and ruby

#+BEGIN_SRC emacs-lisp
(global-rbenv-mode)
(add-hook 'ruby-mode-hook 'robe-mode)
(add-hook 'robe-mode-hook 'ac-robe-setup)
#+END_SRC
